[project]
name = "voice-live-gradio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "azure-identity>=1.24.0",
    "dotenv>=0.9.9",
    "fastapi>=0.116.1",
    "fastrtc>=0.0.29",
    "gradio>=5.42.0",
    "openai>=1.99.9",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.35.0",
]
